package com.tekshop;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

public class Cart extends HttpServlet {
	@Override
	protected void service(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		PrintWriter out = res.getWriter();
		res.setContentType("text/html");
		out.write("<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "    <meta charset='utf-8'>\r\n"
				+ "    <meta http-equiv='X-UA-Compatible' content='IE=edge'>\r\n"
				+ "    <title>Cart</title>\r\n"
				+ "    <meta name='viewport' content='width=device-width, initial-scale=1'>\r\n"
				+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
				+ "	   <style>\r\n"
				+ "		h1{\r\n"
				+ "		    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n"
				+ "		    font-style: oblique;\r\n"
				+ "			text-align: center;\r\n"
				+ "		    color: brown;\r\n"
				+ "		}\r\n"
				+ "	   </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <h1>TekShop</h1>\r\n"
				+ "    <div>\r\n"
				+ "        <div id=\"no-items-div\" style=\"display: none; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: x-large;\">\r\n"
				+ "            No Items in the cart &#128521;\r\n"
				+ "        </div>\r\n"
				+ "        <div id=\"items-main-div\">\r\n"
				+ "            <h2 style=\"font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\">Cart</h2>\r\n"
				+ "            <div id=\"items-root-div\">\r\n"
				+ "            </div>\r\n"
				+ "            <div id=\"bill-div\" style=\"display: none; background-color: aquamarine; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; margin: 5px; border: 1px solid grey; border-radius: 5px;\">\r\n"
				+ "                <form action=\"Checkout\" method=\"post\">\r\n"
				+ "                    <p style=\"text-align: center; font-size: x-large;\"><span><b>Total Bill: </b></span><span id=\"bill-span\"></span></p>\r\n"
				+ "                    <input type=\"hidden\" name=\"order-amount\" id=\"order-amount\">\r\n"
				+ "                    <button type=\"submit\" style=\"margin: 0 auto; display: block; padding: 10px; border-radius: 5px; border: 0.5px solid blue; margin-bottom: 5px; cursor: pointer;\">Place Order</button>\r\n"
				+ "                </form>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "<script>\r\n"
				+ "    totalBill = parseInt('0');\r\n"
				+ "    function populateCart(prod_id,category,imgSrc,prod_name,prod_price,prod_quantity){\r\n"
				+ "        bill=0;\r\n"
				+ "        var mainDiv = document.createElement('div');\r\n"
				+ "        mainDiv.style = \"border: 0.5px solid grey; border-radius: 5px; box-shadow: 1px 0.5px 1px 0.5px grey; width: inherit; margin: 5px; display: flex;\";\r\n"
				+ "\r\n"
				+ "        var img = document.createElement('img');\r\n"
				+ "        img.src = getProductImage(category);\r\n"
				+ "        img.style = \"width: 150px; height: 150px; margin: 5px;\";\r\n"
				+ "        img.alt = prod_name+\"_img\";\r\n"
				+ "\r\n"
				+ "        mainDiv.appendChild(img);\r\n"
				+ "\r\n"
				+ "        var prodDiv = document.createElement('div');\r\n"
				+ "\r\n"
				+ "        var nameP = document.createElement('p');\r\n"
				+ "        var nameB = document.createElement('b');\r\n"
				+ "        nameB.style = \"font-family: Arial, Helvetica, sans-serif;\";\r\n"
				+ "        nameB.innerText = prod_name;\r\n"
				+ "        nameP.appendChild(nameB);\r\n"
				+ "\r\n"
				+ "        var priceP = document.createElement('p');\r\n"
				+ "        var priceI = document.createElement('i');\r\n"
				+ "        priceI.innerText = \"₹ \"+prod_price+\"/-\";\r\n"
				+ "        priceI.style = \"font-family: Verdana, Geneva, Tahoma, sans-serif; color: rgb(113, 208, 113);\";\r\n"
				+ "        priceP.appendChild(priceI);\r\n"
				+ "\r\n"
				+ "        prodDiv.appendChild(nameP);\r\n"
				+ "        prodDiv.appendChild(priceP);\r\n"
				+ "        bill+=parseInt(prod_price)*prod_quantity;\r\n"
				+ "        totalBill+=bill;\r\n"
				+ "        priceI.innerText = \"₹ \"+bill+\"/-\";\r\n"
				+ "        document.getElementById('bill-span').innerText = '₹ '+totalBill+'/-';\r\n"
				+ "		   document.getElementById('order-amount').value=totalBill;\r\n"
				+ "\r\n"
				+ "        var quantityP = document.createElement('p');\r\n"
				+ "        quantityP.style = \"height: 20px;\";\r\n"
				+ "        var quantityDiv = document.createElement('div');\r\n"
				+ "        var minusBtn = document.createElement('button');\r\n"
				+ "        minusBtn.style = \"background-color: white; border: 0.2px solid grey; padding: 5px; cursor: pointer;\";\r\n"
				+ "        var plusBtn = document.createElement('button');\r\n"
				+ "        plusBtn.style = \"background-color: white; border: 0.2px solid grey; padding: 5px; cursor: pointer;\";\r\n"
				+ "        var quantitySpan = document.createElement('span');\r\n"
				+ "        quantitySpan.style = \"margin: 4px; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;\";\r\n"
				+ "        quantitySpan.innerText = prod_quantity;\r\n"
				+ "\r\n"
				+ "        var minusI = document.createElement('i');\r\n"
				+ "        var plusI = document.createElement('i');\r\n"
				+ "\r\n"
				+ "        minusI.classList.add(\"fa\");\r\n"
				+ "        minusI.classList.add(\"fa-minus\");\r\n"
				+ "        plusI.classList.add(\"fa\");\r\n"
				+ "        plusI.classList.add(\"fa-plus\");\r\n"
				+ "\r\n"
				+ "        var quantityForm = document.createElement('form');\r\n"
				+ "        quantityForm.setAttribute('action','UpdateQuantity');\r\n"
				+ "        var quantityInput = document.createElement('input');\r\n"
				+ "        quantityInput.setAttribute('type','hidden');\r\n"
				+ "        quantityInput.name = 'quantity';\r\n"
				+ "        quantityInput.value = prod_quantity;\r\n"
				+ "\r\n"
				+ "        var quantityProduct = document.createElement('input');\r\n"
				+ "        quantityProduct.setAttribute('type','hidden');\r\n"
				+ "        quantityProduct.name = 'product';\r\n"
				+ "        quantityProduct.value = prod_id;\r\n"
				+ "\r\n"
				+ "        quantityForm.appendChild(quantityProduct);\r\n"
				+ "        quantityForm.appendChild(quantityInput);\r\n"
				+ "        quantityForm.appendChild(minusBtn);\r\n"
				+ "        quantityForm.appendChild(quantitySpan);\r\n"
				+ "        quantityForm.appendChild(plusBtn);\r\n"
				+ "\r\n"
				+ "        minusBtn.addEventListener('click',function(){\r\n"
				+ "            var value = parseInt(quantitySpan.innerText);\r\n"
				+ "            if(value>1){\r\n"
				+ "                quantitySpan.innerText = parseInt(quantitySpan.innerText)-1;\r\n"
				+ "                prod_quantity--;\r\n"
				+ "                bill = prod_price*prod_quantity;\r\n"
				+ "                priceI.innerText = \"₹ \"+bill+\"/-\";\r\n"
				+ "                totalBill-=parseInt(prod_price);\r\n"
				+ "                quantityInput.value = prod_quantity;\r\n"
				+ "                document.getElementById('bill-span').innerText = '₹ '+totalBill+'/-';\r\n"
				+ "		   		   document.getElementById('order-amount').value=totalBill;\r\n"
				+ "            }\r\n"
				+ "        });\r\n"
				+ "\r\n"
				+ "        plusBtn.addEventListener('click',function(){\r\n"
				+ "            quantitySpan.innerText = parseInt(quantitySpan.innerText)+1;\r\n"
				+ "            prod_quantity++;\r\n"
				+ "            bill = prod_price*prod_quantity;\r\n"
				+ "            priceI.innerText = \"₹ \"+bill+\"/-\";\r\n"
				+ "            totalBill+=parseInt(prod_price);\r\n"
				+ "            quantityInput.value = prod_quantity;\r\n"
				+ "            document.getElementById('bill-span').innerText = '₹ '+totalBill+'/-';\r\n"
				+ "		       document.getElementById('order-amount').value=totalBill;\r\n"
				+ "        });\r\n"
				+ "\r\n"
				+ "        minusBtn.appendChild(minusI);\r\n"
				+ "        plusBtn.appendChild(plusI);\r\n"
				+ "\r\n"
				+ "        quantityDiv.appendChild(quantityForm);\r\n"
				+ "\r\n"
				+ "        quantityP.appendChild(quantityDiv);\r\n"
				+ "\r\n"
				+ "        prodDiv.appendChild(quantityP);\r\n"
				+ "\r\n"
				+ "        var delDiv = document.createElement('div');\r\n"
				+ "        delDiv.style = \"margin-left: auto; height: max-content;\";\r\n"
				+ "        var delBtn = document.createElement('button');\r\n"
				+ "        delBtn.style = \"float: right; background-color: red; border: 0.2px solid red; border-top-right-radius: 5px; cursor: pointer;\";\r\n"
				+ "        var delI = document.createElement('i');\r\n"
				+ "        delI.classList.add('fa');\r\n"
				+ "        delI.classList.add('fa-trash');\r\n"
				+ "        delI.style = \"color: white;\";\r\n"
				+ "\r\n"
				+ "        delBtn.appendChild(delI);\r\n"
				+ "        \r\n"
				+ "        var delForm = document.createElement('form');\r\n"
				+ "		delForm.setAttribute('action','DeleteProduct');\r\n"
				+ "		\r\n"
				+ "		var delInput = document.createElement('input');\r\n"
				+ "		delInput.setAttribute('type','hidden');\r\n"
				+ "		delInput.value = prod_id;\r\n"
				+ "		delInput.name = 'product';\r\n"
				+ "		\r\n"
				+ "		delBtn.setAttribute('type','submit');\r\n"
				+ "		\r\n"
				+ "		delForm.appendChild(delInput);\r\n"
				+ "		delForm.appendChild(delBtn);\r\n"
				+ "		\r\n"
				+ "		delDiv.appendChild(delForm);\r\n"
				+ "\r\n"
				+ "        mainDiv.appendChild(prodDiv);\r\n"
				+ "        mainDiv.appendChild(delDiv);\r\n"
				+ "\r\n"
				+ "        document.getElementById('items-root-div').appendChild(mainDiv);\r\n"
				+ "    }\r\n"
				+ "    \r\n"
				+ "    function getProductImage(category){\r\n"
				+ "	    imagePath = \"\";\r\n"
				+ "	    switch (category) {\r\n"
				+ "	        case \"Apparels_Accessories\":\r\n"
				+ "	            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494689/Tekshop/apparels-accessories_uc5o8e.jpg\";\r\n"
				+ "	            break;\r\n"
				+ "	        case \"Style_Fashion\":\r\n"
				+ "	            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494689/Tekshop/style-fashion_zghqmi.jpg\";\r\n"
				+ "	            break;\r\n"
				+ "	        case \"Home_Garden\":\r\n"
				+ "	            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494689/Tekshop/home-garden_qizt5h.jpg\";\r\n"
				+ "	            break;\r\n"
				+ "	        case \"Sporting_Goods\":\r\n"
				+ "	            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494689/Tekshop/sport-goods_bwx7ct.jpg\";\r\n"
				+ "	            break;\r\n"
				+ "	        case \"Health_Wellness\":\r\n"
				+ "	            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494688/Tekshop/health-wellness_nnms3f.png\";\r\n"
				+ "	            break;\r\n"
				+ "	        case \"Children_Infants\":\r\n"
				+ "	            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494687/Tekshop/children-infant_x7vls8.png\";\r\n"
				+ "	            break;\r\n"
				+ "	        case \"Groceries_Food_Drinks\":\r\n"
				+ "	            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494688/Tekshop/groceries_h5drlm.jpg\";\r\n"
				+ "	            break;\r\n"
				+ "	        case \"Flowers_Gifts\":\r\n"
				+ "	            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494688/Tekshop/flower-gift_zvrgvp.jpg\";\r\n"
				+ "	            break;\r\n"
				+ "	        default:\r\n"
				+ "	            break;\r\n"
				+ "	    }\r\n"
				+ "	    return imagePath;\r\n"
				+ "	}\r\n"
				+ "</script>\r\n"
				+ "</html>");
		List<HashMap<String,String>> cartItems;
			try {
				CartDAO dao = new CartDAO();
				cartItems = CartDAO.cartItems();
				Iterator<HashMap<String, String>> listIterator = cartItems.iterator();
				if(listIterator.hasNext()) {
					while(listIterator.hasNext()) {
						HashMap<String, String> item = listIterator.next();
						out.append("<script>document.getElementById('no-items-div').style.display = 'none'; document.getElementById('bill-div').style.display='block'; populateCart('"+item.get("ProductID")+"','"+item.get("ProductCategory")+"','','"+item.get("ProductName")+"','"+item.get("ProductPrice")+"','"+item.get("SelectedUnits")+"');</script>");
					}
				}else {
					out.write("<script>document.getElementById('no-items-div').style.display = 'block'; document.getElementById('items-main-div').style.display = 'none';</script>");
				}
			} catch (SQLException | ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
}
