package com.tekshop;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.List;

public class HomePage extends HttpServlet {
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		HomePageDAO hpd = new HomePageDAO();
		List<HashMap<String,String>> products;
		try {
			products = hpd.getProducts();
			PrintWriter out = res.getWriter();
			res.setContentType("text/html");
			out.write("<!DOCTYPE html>\r\n"
					+ "<html>\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "    <meta charset='utf-8'>\r\n"
					+ "    <meta http-equiv='X-UA-Compatible' content='IE=edge'>\r\n"
					+ "    <title>TekShop</title>\r\n"
					+ "    <meta name='viewport' content='width=device-width, initial-scale=1'>\r\n"
					+ "    <style>\r\n"
					+ "    	*{\r\n"
					+ "		    margin: 0;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		body{\r\n"
					+ "		    background-color: rgb(241, 244, 246);\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		#top-div{\r\n"
					+ "		    width: 100%;\r\n"
					+ "		    text-align: center;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		#search-div{\r\n"
					+ "		    display: inline-block;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		input[type=search]{\r\n"
					+ "		    width: 250px;\r\n"
					+ "		    height: 40px;\r\n"
					+ "		    border-radius: 5px;\r\n"
					+ "		    border: 0.5px solid gainsboro;\r\n"
					+ "		    box-shadow: 1px 1px 1px grey;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		#search-btn{\r\n"
					+ "		    padding: 10px;\r\n"
					+ "		    border-radius: 5px;\r\n"
					+ "		    border: none;\r\n"
					+ "		    box-shadow: 1px 1px 1px blueviolet;\r\n"
					+ "		    background-color: blueviolet;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		#search-btn i{\r\n"
					+ "		    color: white;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		#top-div h1{\r\n"
					+ "		    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n"
					+ "		    font-style: oblique;\r\n"
					+ "		    color: brown;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		.root-div{\r\n"
					+ "		    display: none;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		#products-div{\r\n"
					+ "		    margin: 5px;\r\n"
					+ "		    flex-wrap: wrap;\r\n"
					+ "		    display: flex;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		#sort-filter-div{\r\n"
					+ "		    width: max-content;\r\n"
					+ "		    margin: 5px;\r\n"
					+ "		    padding: 10px;\r\n"
					+ "		    border-radius: 5px;\r\n"
					+ "		    box-shadow: 0.5px 1px 1px 1.32px grey;\r\n"
					+ "		    border: none;\r\n"
					+ "		}\r\n"
					+ "		\r\n"
					+ "		input[type=range]{\r\n"
					+ "		    width: 100%;\r\n"
					+ "		}\r\n"
					+ "    </style>\r\n"
					+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body>\r\n"
					+ "    <div id=\"top-div\">\r\n"
					+ "        <h1>TekShop</h1>\r\n"
					+ "        <div id=\"search-div\">\r\n"
					+ "            <input list=\"products-list\" type=\"search\" placeholder=\"Search\" id=\"search-input\">\r\n"
					+ "            <datalist id=\"products-list\"></datalist>\r\n"
					+ "            <button id=\"search-btn\"><i class=\"fa fa-search\"></i></button>\r\n"
					+ "        </div>\r\n"
					+ "    </div>\r\n"
					+ "    <div class=\"root-div\" id=\"root-div\">\r\n"
					+ "        <div id=\"sort-filter-div\">\r\n"
					+ "            <div>\r\n"
					+ "                <p>Price range</p>\r\n"
					+ "                <input type=\"range\" id=\"price-range\">\r\n"
					+ "                <p></p>\r\n"
					+ "            </div>\r\n"
					+ "            <div>\r\n"
					+ "                <p><b>Category:</b></p>\r\n"
					+ "                <div>\r\n"
					+ "                    <input type=\"checkbox\"><span>Apparels & Accessories</span><br>\r\n"
					+ "                    <input type=\"checkbox\"><span>Style & Fashion</span><br>\r\n"
					+ "                    <input type=\"checkbox\"><span>Home & Garden</span>\r\n"
					+ "                    <br>\r\n"
					+ "                    <input type=\"checkbox\"><span>Sporting Goods</span>\r\n"
					+ "                    <br>\r\n"
					+ "                    <input type=\"checkbox\"><span>Health & Wellness</span>\r\n"
					+ "                    <br>\r\n"
					+ "                    <input type=\"checkbox\"><span>Children & Infants</span>\r\n"
					+ "                    <br>\r\n"
					+ "                    <input type=\"checkbox\"><span>Groceries, Food and Drinks</span>\r\n"
					+ "                    <br>\r\n"
					+ "                    <input type=\"checkbox\"><span>Flowers and Gifts</span>\r\n"
					+ "                </div>\r\n"
					+ "            </div>\r\n"
					+ "        </div>\r\n"
					+ "        <div id=\"products-div\">\r\n"
					+ "            \r\n"
					+ "        </div>\r\n"
					+ "    </div>\r\n"
					+ "</body>\r\n"
					+ "<script>\r\n"
					+ "	document.getElementById(\"price-range\").addEventListener('change',function(){\r\n"
					+ "	    filterProducts(\"price\");\r\n"
					+ "	});\r\n"
					+ "	\r\n"
					+ "	document.getElementById(\"search-btn\").addEventListener('click',function(){\r\n"
					+ "	    var searchInput = document.getElementById('search-input').value;\r\n"
					+ "	    if(searchInput.length>0){\r\n"
					+ "	        searchProduct(searchInput);\r\n"
					+ "	    }\r\n"
					+ "	});\r\n"
					+ "	\r\n"
					+ "	function populateProduct(category,prod_name,prod_price){\r\n"
					+ "	        document.getElementById(\"root-div\").style.display = \"flex\";\r\n"
					+ "	    if(true){\r\n"
					+ "	        var div = document.createElement('div');\r\n"
					+ "	        div.style = \"border: 0.1px solid rgb(230, 206, 206); border-radius:5px; width: max-content; margin: 5px; padding: 10px; background-color:white;\";\r\n"
					+ "	\r\n"
					+ "	        var img = document.createElement('img');\r\n"
					+ "	        img.src = getProductImage(category);\r\n"
					+ "	        img.style = \"width:200px; margin:0 auto; display:block;\";\r\n"
					+ "	        img.alt = prod_name+\"_img\";\r\n"
					+ "	\r\n"
					+ "	        var p = document.createElement('p');\r\n"
					+ "	        var b = document.createElement('b');\r\n"
					+ "	\r\n"
					+ "	        p.appendChild(b);\r\n"
					+ "	        b.innerText = prod_name;\r\n"
					+ "	        b.style.fontFamily = \"'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif\";\r\n"
					+ "	        b.style.fontSize = \"large\";\r\n"
					+ "	        p.style.textAlign = \"center\";\r\n"
					+ "	\r\n"
					+ "	        var p1 = document.createElement('p');\r\n"
					+ "	        var b1 = document.createElement('b');\r\n"
					+ "	        b1.innerText = \"Price: \";\r\n"
					+ "	        b1.style.fontFamily = \"Lucida Sans, 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif\";\r\n"
					+ "	        p1.appendChild(b1);\r\n"
					+ "	        var span = document.createElement('span');\r\n"
					+ "	        span.innerText = \"₹ \"+prod_price+\"/-\";\r\n"
					+ "	        span.style.fontSize = \"20px\";\r\n"
					+ "	        span.style.color = \"green\";\r\n"
					+ "	        span.style.fontFamily = \"Arial, Helvetica, sans-serif\";\r\n"
					+ "	        span.style.fontStyle = \"italic\";\r\n"
					+ "	        p1.appendChild(span);\r\n"
					+ "	\r\n"
					+ "	        var div1 = document.createElement('div');\r\n"
					+ "	        div1.style = \"width: max-content; margin: 0 auto; display: block;\";\r\n"
					+ "	\r\n"
					+ "	        var view_details_btn = document.createElement('button');\r\n"
					+ "	        var view_details_icon = document.createElement('i');\r\n"
					+ "	        view_details_icon.classList.add(\"fa\");\r\n"
					+ "	        view_details_icon.classList.add(\"fa-info-circle\");\r\n"
					+ "	        view_details_icon.style.fontSize = \"large\";\r\n"
					+ "	\r\n"
					+ "	        view_details_btn.innerText = \"View details \";\r\n"
					+ "	\r\n"
					+ "	        view_details_btn.appendChild(view_details_icon);\r\n"
					+ "	        view_details_btn.style.margin = \"5px\";\r\n"
					+ "	        view_details_btn.style.cursor = \"pointer\";\r\n"
					+ "	\r\n"
					+ "	        var purchase_btn = document.createElement('button');\r\n"
					+ "	        var purchase_icon = document.createElement('i');\r\n"
					+ "	        purchase_icon.classList.add(\"fa\");\r\n"
					+ "	        purchase_icon.classList.add(\"fa-shopping-bag\");\r\n"
					+ "	        purchase_icon.style.fontSize = \"large\";\r\n"
					+ "	        purchase_btn.innerText = \"Purchase \";\r\n"
					+ "	\r\n"
					+ "	        purchase_btn.appendChild(purchase_icon);\r\n"
					+ "	        purchase_btn.style.cursor = \"pointer\";\r\n"
					+ "	\r\n"
					+ "	        div1.appendChild(view_details_btn);\r\n"
					+ "	        div1.appendChild(purchase_btn);\r\n"
					+ "	\r\n"
					+ "	        div.appendChild(img);\r\n"
					+ "	        div.appendChild(p);\r\n"
					+ "	        div.appendChild(p1);\r\n"
					+ "	        div.appendChild(div1);\r\n"
					+ "	\r\n"
					+ "	        view_details_btn.addEventListener('click',function(){\r\n"
					+ "	            window.open(\"view-product-details.html?Product=\"+prod_name,\"_blank\",\"width:200px,height:200px\");\r\n"
					+ "	        });\r\n"
					+ "	\r\n"
					+ "	        purchase_btn.addEventListener('click',function(){\r\n"
					+ "	\r\n"
					+ "	        });\r\n"
					+ "	\r\n"
					+ "	        document.getElementById(\"products-div\").appendChild(div);\r\n"
					+ "	    }\r\n"
					+ "	}\r\n"
					+ "	\r\n"
					+ "	function getProductImage(category){\r\n"
					+ "	    imagePath = \"\";\r\n"
					+ "	    switch (category) {\r\n"
					+ "	        case \"Apparels_Accessories\":\r\n"
					+ "            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494689/Tekshop/apparels-accessories_uc5o8e.jpg\";\r\n"
					+ "            break;\r\n"
					+ "        case \"Style_Fashion\":\r\n"
					+ "            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494689/Tekshop/style-fashion_zghqmi.jpg\";\r\n"
					+ "            break;\r\n"
					+ "        case \"Home_Garden\":\r\n"
					+ "            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494689/Tekshop/home-garden_qizt5h.jpg\";\r\n"
					+ "            break;\r\n"
					+ "        case \"Sporting_Goods\":\r\n"
					+ "            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494689/Tekshop/sport-goods_bwx7ct.jpg\";\r\n"
					+ "            break;\r\n"
					+ "        case \"Health_Wellness\":\r\n"
					+ "            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494688/Tekshop/health-wellness_nnms3f.png\";\r\n"
					+ "            break;\r\n"
					+ "        case \"Children_Infants\":\r\n"
					+ "            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494687/Tekshop/children-infant_x7vls8.png\";\r\n"
					+ "            break;\r\n"
					+ "        case \"Groceries_Food_Drinks\":\r\n"
					+ "            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494688/Tekshop/groceries_h5drlm.jpg\";\r\n"
					+ "            break;\r\n"
					+ "        case \"Flowers_Gifts\":\r\n"
					+ "            imagePath = \"https://res.cloudinary.com/chennupati-balu/image/upload/v1651494688/Tekshop/flower-gift_zvrgvp.jpg\";\r\n"
					+ "            break;\r\n"
					+ "	        default:\r\n"
					+ "	            break;\r\n"
					+ "	    }\r\n"
					+ "	    return imagePath;\r\n"
					+ "	}\r\n"
					+ "	\r\n"
					+ "	function filterProducts(filter){\r\n"
					+ "	    switch (filter) {\r\n"
					+ "	        case \"price\":\r\n"
					+ "	            filterByPrice(document.getElementById(\"price-range\").value);\r\n"
					+ "	            break;\r\n"
					+ "	    \r\n"
					+ "	        default:\r\n"
					+ "	            break;\r\n"
					+ "	    }\r\n"
					+ "	}\r\n"
					+ "	\r\n"
					+ "	function filterByPrice(price){\r\n"
					+ "	    var productsDiv = document.getElementById(\"products-div\");\r\n"
					+ "	    productsDiv.innerHTML = \"\";\r\n"
					+ "	\r\n"
					+ "	    var products = getProducts();\r\n"
					+ "	\r\n"
					+ "	    if(products.length>0){\r\n"
					+ "	        for(let i=0;i<products.length;i++){\r\n"
					+ "	            var product = JSON.parse(products[i]);\r\n"
					+ "	            if(product.Unit_Price<=price){\r\n"
					+ "	                populateProduct(product.Category,product.Product_Name,product.Unit_Price,product.Active_Flag);\r\n"
					+ "	            }\r\n"
					+ "	        }\r\n"
					+ "	    }\r\n"
					+ "	}\r\n"
					+ "	\r\n"
					+ "	function filterByCategory(){\r\n"
					+ "	\r\n"
					+ "	}\r\n"
					+ "	\r\n"
					+ "	function searchProduct(search){\r\n"
					+ "	    var productsDiv = document.getElementById(\"products-div\");\r\n"
					+ "	    productsDiv.innerHTML = \"\";\r\n"
					+ "	\r\n"
					+ "	    var products = getProducts();\r\n"
					+ "	\r\n"
					+ "	    if(products.length>0){\r\n"
					+ "	        for(let i=0;i<products.length;i++){\r\n"
					+ "	            var product = JSON.parse(products[i]);\r\n"
					+ "	            if(product.Product_Name==search){\r\n"
					+ "	                populateProduct(product.Category,product.Product_Name,product.Unit_Price,product.Active_Flag);\r\n"
					+ "	            }\r\n"
					+ "	        }\r\n"
					+ "	    }\r\n"
					+ "	}\r\n"
					+ "</script>\r\n"
					+ "</html>");
			for(HashMap<String,String> map: products) {
				System.out.println(map.get("ActiveFlag")+","+Boolean.parseBoolean(map.get("ActiveFlag")));
				if(Boolean.parseBoolean(map.get("ActiveFlag"))==true) {
				out.append("<script>populateProduct('"+map.get("Product_Category")+"','"+map.get("Product_Name")+"','"+map.get("Product_Unit_Price")+"',);</script>");
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
