package com.tekshop;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

public class merchant extends HttpServlet {
	
	protected void service(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		PrintWriter out = res.getWriter();
		res.setContentType("text/html");
		out.write("<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "    <meta charset='utf-8'>\r\n"
				+ "    <meta http-equiv='X-UA-Compatible' content='IE=edge'>\r\n"
				+ "    <title>Tekshop Merchant</title>\r\n"
				+ "    <meta name='viewport' content='width=device-width, initial-scale=1'>\r\n"
				+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
				+ "    <style>\r\n"
				+ "        th{\r\n"
				+ "            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\r\n"
				+ "            padding: 10px;\r\n"
				+ "            font-weight: lighter;\r\n"
				+ "            background-color: rgb(30, 183, 76);\r\n"
				+ "            color: white;\r\n"
				+ "        }\r\n"
				+ "        table{\r\n"
				+ "            width: max-content;\r\n"
				+ "            margin: 0 auto;\r\n"
				+ "            border-radius: 5px;\r\n"
				+ "            background-color: rgb(55, 51, 51);\r\n"
				+ "        }\r\n"
				+ "        table,tr,th,td{\r\n"
				+ "            border: 0.5px solid grey;\r\n"
				+ "        }\r\n"
				+ "        td{\r\n"
				+ "            background-color: rgb(246, 246, 235);\r\n"
				+ "			   text-align: center;\r\n"
				+ "			   font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;\r\n"
				+ "        }\r\n"
				+ "        #revenue-div, #inv-div{\r\n"
				+ "            display: none;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <h2 style=\"text-align: center; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif; font-size: xx-large;\">Merchant</h2>\r\n"
				+ "    <div style=\"border: 0.5px solid grey; border-top: none; border-right: none; border-left: none;\">\r\n"
				+ "        <button id=\"trans-btn\" onclick=\"openTransactions();\" style=\"cursor:pointer; font-size: large; background-color: white; border: 5px solid rgb(92, 119, 181); border-radius: 5px; border-bottom: none; padding: 20px;\">Transactions</button>\r\n"
				+ "        <button id=\"revenue-btn\" onclick=\"openRevenue();\" style=\"cursor:pointer; font-size: large; background-color: white; border: 0.5px solid grey; border-left: none; border-bottom: none; padding: 20px;\">Revenue</button>\r\n"
				+ "        <button id=\"inv-btn\" onclick=\"openInventory();\" style=\"cursor:pointer; font-size: large; background-color: white; border: 0.5px solid grey; border-left: none; border-bottom: none; padding: 20px;\">Inventory</button>\r\n"
				+ "    </div>\r\n"
				+ "    <br>\r\n"
				+ "    <div id=\"trans-div\">\r\n"
				+ "        <table id=\"trans-table\">\r\n"
				+ "            <tr>\r\n"
				+ "                <th>Purchase ID</th>\r\n"
				+ "                <th>Customer ID</th>\r\n"
				+ "                <th>Payment method</th>\r\n"
				+ "                <th>Total Value (without discount %)</th>\r\n"
				+ "                <th>Discount ID</th>\r\n"
				+ "                <th>Final value</th>\r\n"
				+ "            </tr>\r\n"
				+ "        </table>\r\n"
				+ "    </div>\r\n"
				+ "    <div id=\"revenue-div\">\r\n"
				+ "        <table id=\"revenue-table\">\r\n"
				+ "            <tr>\r\n"
				+ "                <td>\r\n"
				+ "                    <span>Filter: </span>\r\n"
				+ "                    <form id=\"revenue-filter-form\">\r\n"
				+ "                        <select name=\"filter\">\r\n"
				+ "                            <option value=\"one_month\">Last 1 month</option>\r\n"
				+ "                            <option value=\"one_quarter\">Last 1 quarter</option>\r\n"
				+ "                            <option value=\"one_year\">Last 1 year</option>\r\n"
				+ "                        </select>\r\n"
				+ "                    </form>\r\n"
				+ "                </td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "                <th>Product ID</th>\r\n"
				+ "                <th>Product Name</th>\r\n"
				+ "                <th>Units sold</th>\r\n"
				+ "                <th>Sold price</th>\r\n"
				+ "            </tr>\r\n"
				+ "        </table>\r\n"
				+ "    </div>\r\n"
				+ "    <div id=\"inv-div\">\r\n"
				+ "        <table id=\"inv-table\">\r\n"
				+ "            <tr>\r\n"
				+ "                <th>Product ID</th>\r\n"
				+ "                <th>Product Name</th>\r\n"
				+ "                <th>Category</th>\r\n"
				+ "                <th>Price</th>\r\n"
				+ "                <th>Inventory</th>\r\n"
				+ "            </tr>\r\n"
				+ "        </table>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "<script>\r\n"
				+ "\r\n"
				+ "    function addInventoryRow(prod_id,prod_name,category,price,inventory){\r\n"
				+ "        var tr = document.createElement('tr');\r\n"
				+ "\r\n"
				+ "        var prodId = document.createElement('td');\r\n"
				+ "        prodId.innerText = prod_id;\r\n"
				+ "\r\n"
				+ "        var prodName = document.createElement('td');\r\n"
				+ "        prodName.innerText = prod_name;\r\n"
				+ "\r\n"
				+ "        var prodCategory = document.createElement('td');\r\n"
				+ "        prodCategory.innerText = category;\r\n"
				+ "\r\n"
				+ "        var prodPrice = document.createElement('td');\r\n"
				+ "        prodPrice.innerText = price;\r\n"
				+ "\r\n"
				+ "        var prodInventory = document.createElement('td');\r\n"
				+ "        prodInventory.innerText = inventory;\r\n"
				+ "\r\n"
				+ "		   if(parseInt(inventory)<=10){\r\n"
				+ "            prodInventory.style.backgroundColor = 'red';\r\n"
				+ "            prodInventory.style.color = 'white';\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "		   if(parseInt(inventory)>10 && parseInt(inventory)<=20){\r\n"
				+ "            prodInventory.style.backgroundColor = 'orange';\r\n"
				+ "            prodInventory.style.color = 'white';\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        var editInvForm = document.createElement('form');\r\n"
				+ "        editInvForm.setAttribute('action','updateInventory');\r\n"
				+ "        editInvForm.setAttribute('type','action');\r\n"
				+ "\r\n"
				+ "        var prodIdInput = document.createElement('input');\r\n"
				+ "        prodIdInput.setAttribute('type','hidden');\r\n"
				+ "        prodIdInput.name = \"productId\";\r\n"
				+ "		   prodIdInput.value = prod_id;\r\n"
				+ "\r\n"
				+ "        var invInput = document.createElement('input');\r\n"
				+ "        invInput.setAttribute('type','number');\r\n"
				+ "		   invInput.value = inventory;\r\n"
				+ "		   invInput.style = \"margin: 5px;\"\r\n"
				+ "        invInput.name = \"inventory\";\r\n"
				+ "\r\n"
				+ "        var updateBtn = document.createElement('button');\r\n"
				+ "        updateBtn.setAttribute('type','submit');\r\n"
				+ "        updateBtn.innerText = 'Update';\r\n"
				+ "        updateBtn.style = \"width: max-content; cursor: pointer; padding: 5px; background-color: blue; color: white; border: none; box-shadow: 1px 1px 1px grey;\";\r\n"
				+ "        \r\n"
				+ "        editInvForm.appendChild(prodIdInput);\r\n"
				+ "        editInvForm.appendChild(invInput);\r\n"
				+ "        editInvForm.appendChild(updateBtn);\r\n"
				+ "\r\n"
				+ "        var prodInvButton = document.createElement('button');\r\n"
				+ "        prodInvButton.style = \"border: none; width: max-content; background-color: white; margin: 4px;\";\r\n"
				+ "        var prodInvButtonI = document.createElement('i');\r\n"
				+ "        prodInvButtonI.classList.add('fa');\r\n"
				+ "        prodInvButtonI.classList.add('fa-edit');\r\n"
				+ "        prodInvButton.appendChild(prodInvButtonI);\r\n"
				+ "\r\n"
				+ "        prodInventory.appendChild(prodInvButton);\r\n"
				+ "\r\n"
				+ "        prodInvButton.addEventListener('click',function(){\r\n"
				+ "            prodInventory.appendChild(editInvForm);\r\n"
				+ "        });\r\n"
				+ "\r\n"
				+ "        tr.appendChild(prodId);\r\n"
				+ "        tr.appendChild(prodName);\r\n"
				+ "        tr.appendChild(prodCategory);\r\n"
				+ "        tr.appendChild(prodPrice);\r\n"
				+ "        tr.appendChild(prodInventory);\r\n"
				+ "\r\n"
				+ "        document.getElementById('inv-table').appendChild(tr);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    function addRevenueRow(prod_id,prod_name,units,price){\r\n"
				+ "        var tr = document.createElement('tr');\r\n"
				+ "\r\n"
				+ "        var prodId = document.createElement('td');\r\n"
				+ "        prodId.innerText = prod_id;\r\n"
				+ "\r\n"
				+ "        var prodName = document.createElement('td');\r\n"
				+ "        prodName.innerText = prod_name;\r\n"
				+ "\r\n"
				+ "        var prodUnits = document.createElement('td');\r\n"
				+ "        prodUnits.innerText = units;\r\n"
				+ "\r\n"
				+ "        var prodPrice = document.createElement('td');\r\n"
				+ "        prodPrice.innerText = price;\r\n"
				+ "\r\n"
				+ "        tr.appendChild(prodId);\r\n"
				+ "        tr.appendChild(prodName);\r\n"
				+ "        tr.appendChild(prodUnits);\r\n"
				+ "        tr.appendChild(prodPrice);\r\n"
				+ "\r\n"
				+ "        document.getElementById('revenue-table').appendChild(tr);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    function addTransactionRow(purchase_id,cus_id,payment_method,total_value,dis_id,final_value){\r\n"
				+ "        var tr = document.createElement('tr');\r\n"
				+ "\r\n"
				+ "        var purchase = document.createElement('td');\r\n"
				+ "        purchase.innerText = purchase_id;\r\n"
				+ "\r\n"
				+ "        var cusId = document.createElement('td');\r\n"
				+ "        cusId.innerText = cus_id;\r\n"
				+ "\r\n"
				+ "        var paymentMethod = document.createElement('td');\r\n"
				+ "        paymentMethod.innerText = payment_method;\r\n"
				+ "\r\n"
				+ "        var totalValue = document.createElement('td');\r\n"
				+ "        totalValue.innerText = total_value;\r\n"
				+ "\r\n"
				+ "        var discount = document.createElement('td');\r\n"
				+ "        discount.innerText = dis_id;\r\n"
				+ "\r\n"
				+ "        var finalValue = document.createElement('td');\r\n"
				+ "        finalValue.innerText = final_value;\r\n"
				+ "\r\n"
				+ "        tr.appendChild(purchase);\r\n"
				+ "        tr.appendChild(cusId);\r\n"
				+ "        tr.appendChild(paymentMethod);\r\n"
				+ "        tr.appendChild(totalValue);\r\n"
				+ "        tr.appendChild(discount);\r\n"
				+ "        tr.appendChild(finalValue);\r\n"
				+ "\r\n"
				+ "        document.getElementById('trans-table').appendChild(tr);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    function openTransactions(){\r\n"
				+ "        document.getElementById('trans-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 5px solid rgb(92, 119, 181); border-radius: 5px; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('revenue-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 0.5px solid grey; border-left: none; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('inv-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 0.5px solid grey; border-left: none; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('trans-div').style.display = 'block';\r\n"
				+ "        document.getElementById('revenue-div').style.display = 'none';\r\n"
				+ "        document.getElementById('inv-div').style.display = 'none';\r\n"
				+ "    }\r\n"
				+ "    function openRevenue(){\r\n"
				+ "        document.getElementById('revenue-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 5px solid rgb(92, 119, 181); border-radius: 5px; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('trans-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 0.5px solid grey; border-right: none; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('inv-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 0.5px solid grey; border-left: none; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('trans-div').style.display = 'none';\r\n"
				+ "        document.getElementById('revenue-div').style.display = 'block';\r\n"
				+ "        document.getElementById('inv-div').style.display = 'none';\r\n"
				+ "    }\r\n"
				+ "    function openInventory(){\r\n"
				+ "        document.getElementById('inv-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 5px solid rgb(92, 119, 181); border-radius: 5px; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('revenue-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 0.5px solid grey; border-right: none; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('trans-btn').style = \"cursor:pointer; font-size: large; background-color: white; border: 0.5px solid grey; border-right: none; border-bottom: none; padding: 20px;\";\r\n"
				+ "        document.getElementById('trans-div').style.display = 'none';\r\n"
				+ "        document.getElementById('revenue-div').style.display = 'none';\r\n"
				+ "        document.getElementById('inv-div').style.display = 'block';\r\n"
				+ "    }\r\n"
				+ "</script>\r\n"
				+ "</html>");
		
		MerchantDAO dao;
		
		try {
			dao = new MerchantDAO();
			
			List<HashMap<String,String>> transactions = dao.getTransactions();
			List<HashMap<String,String>> revenues = dao.getRevenue();
			List<HashMap<String,String>> inventories = dao.getInventories();
			
			Iterator<HashMap<String, String>> transactionIterator = transactions.iterator();
			Iterator<HashMap<String, String>> revenueIterator = revenues.iterator();
			Iterator<HashMap<String, String>> inventoryIterator = inventories.iterator();
			
			while(transactionIterator.hasNext()) {
				HashMap<String,String> transaction = transactionIterator.next();
				out.append("<script>addTransactionRow('"+transaction.get("PurchaseID")+"','"+transaction.get("CustomerID")+"','"+transaction.get("PaymentMethod")+"','"+transaction.get("TotalValue")+"','"+transaction.get("DiscountID")+"','"+transaction.get("FinalValue")+"');</script>");
			}
			
			while(revenueIterator.hasNext()) {
				HashMap<String,String> revenue = revenueIterator.next();
				out.append("<script>addRevenueRow('"+revenue.get("ProductID")+"','"+revenue.get("ProductName")+"','"+revenue.get("ProductUnits")+"','"+revenue.get("ProductRevenue")+"');</script>");
			}
			
			while(inventoryIterator.hasNext()) {
				HashMap<String,String> inventory = inventoryIterator.next();
				out.append("<script>addInventoryRow('"+inventory.get("ProductID")+"','"+inventory.get("ProductName")+"','"+inventory.get("ProductCategory")+"','"+inventory.get("ProductPrice")+"','"+inventory.get("ProductInventory")+"');</script>");
			}
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

}
